image_parameters:
  height_og: 450
  img_path: static_frame_from_video.jpg
  p1:
  - 12
  - 87
  p2:
  - 583
  - 88
  p3:
  - 588
  - 431
  p4:
  - 13
  - 434
  p5:
  - 403
  - 181
  p6:
  - 400
  - 129
  size_frame: 600
  width_og: 600
