image_parameters:
  height_og: 450
  img_path: static_frame_from_video.jpg
  p1:
  - 302
  - 103
  p2:
  - 595
  - 136
  p3:
  - 490
  - 442
  p4:
  - 0
  - 321
  p5:
  - 192
  - 269
  p6:
  - 397
  - 316
  size_frame: 600
  width_og: 600
